### ISSUE TITLE
Allow orga-files/folders to be accessible in meetings

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-meta#121]
**Desired behaviour:**
- If a file/folder is public then this file/folder needs to be displayed in every meeting
- Files/folders need a new flag to show that they are public.

**Comment by luisa-beerboom** [comment]
After discussions with @bastianjoel we've come to the conclusion that the mediafiles meeting or organization specific data should be migrated to their own connective collections, since otherwise the requirement on setting access groups per meeting will not be solvable in a satisfactory manner
