### ISSUE TITLE
A user with userCanUpdate in a meeting should be allowed to see organization_management_level of users.

### ISSUE THREAD

**Issue by reiterl** [OpenSlides/openslides-meta#87]
See https://github.com/OpenSlides/openslides-client/issues/3591

To check, if a user can change a Password of another user, they needs to know the organization_managment_level.
With introducing `user.canUpdate` and allowing them to change passwords, this need appears.

**Comment by Elblinator** [comment]
I talked with @emanuelschuetze about it and it is okay to set the restriction mode from organization_managment_level to B
